=== hychen/iclang/schema/hyperscript-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "ICLang Program",
    "type": "object",
    "required":["properties", "processes", "connections"],
    "properties": {
        "comment": {"$ref":"#/definitions/comment"},
        "properties": {"$ref":"#/definitions/properties"},
        "processes": {"$ref":"#/definitions/processes"},
        "connections": {"$ref":"#/definitions/connections"},
        "inports": {"$ref":"#/definitions/inports"},
        "exports": {"$ref":"#/definitions/exports"}
    },
    "definitions":{        
        "properties":{
            "title": "IClang Program Properties",
            "type":"object",
            "properties":{
                "name":{
                    "title": "IClang Program Name",                    
                    "type":"string",
                    "required": true
                },
                "description":{
                    "title": "IClang Program Description",
                    "type":"string",
                    "required": true
                }
            }
        },
        "processes":{
            "title": "Running Processes",
            "type":"object",
            "addtionalProperties":false,
            "patternProperties":{
                "^[a-zA-Z]([a-zA-Z0-9]*?)":{
                    "type":"object",
                    "required":["component", "option"],
                    "properties":{
                        "component":{
                            "title": "Component",
                            "type":"string"
                        },
                        "option":{
                            "title": "Component Option",
                            "type":"object"
                        }
                    }
                }
            }
        },
        "process_port":{
            "title": "Process Port",
            "type":"object",
            "required":["process", "port"],
            "properties":{
                "process":{
                    "title": "Process Name",
                    "type":"string"
                },
                "port":{
                    "title": "Port Name",
                    "type":"string"
                }
            }
        },
        "connections":{
            "title": "Connections",
            "type":"array",
            "items":{
                "type":"object",
                "required": ["src", "dest"],
                "properties":{
                    "src":{"$ref":"#/definitions/process_port"},
                    "dest":{"$ref":"#/definitions/process_port"}
                }
            }
        },
        "inports":{
            "title": "Program InPorts",
            "type":"array",
            "items":{
                "type":"object",
                "required":["name","dest"],
                "properties":{
                    "name":{
                        "title": "InPort Name",
                        "type":"string"
                    },
                    "dest":{
                        "$ref":"#/definitions/process_port"
                    }
                }
            }
        },
        "exports":{
            "title": "Program ExPorts",
            "type":"array",
            "items":{
                "required":["name", "src"],
                "type":"object",
                "properties":{
                    "name":{
                        "title": "ExPort Name",
                        "type":"string"
                    },
                    "src":{
                        "$ref":"#/definitions/process_port"
                    }
                }
            }
        },
        "comment":{
            "title": "Program Comment",
            "type":"string"
        }        
    }
}

=== hychen/iclang/example/watchdog.json
{
    "properties":{
        "name":"read CNN last news",
        "description": "subscribe CNN last news feed and print to console."
    },
    "processes":{
        "SubCNN":{
            "component": "subscribe-rss",
            "arguments": {
            	"feed": "http://rss.cnn.com/rss/cnn_latest.rss"
            },
            "options": {
            	"return-type": "item"
            }
        },
        "Print":{
            "component":"print"
        }
    },
    "connections":[
        {
            "src":{
                "process":"SubCNN",
                "port":"out"
            },
            "dest":{
                "process":"Print",
                "port":"in"
            }
        }
    ],
    "inports":[
        {
            "name":"str",
            "dest":{
                "process":"SubCNN",
                "port":"in"
            }
        }
    ],
    "exports":[
        {
            "name":"status",
            "src":{
                "process":"Print",
                "port":"out"
            }
        }
    ]
}
